.TH smsClean 1 "2008 Feb 22" GNU
.SH NAME
smsClean - Program to clean the SMS analysis files. 
.SH SYNOPSIS
.B smsClean
.I inputSoundFile outputSmsFile
.SH DESCRIPTION
\fISMS\fP is a set of techniques and software implementations for the
analysis, transformation and synthesis of musical sounds based on a
sinusoidal plus residual model. These techniques can be used for
synthesis, processing and coding applications, while some of the
intermediate results might also be applied to other music related
problems, such as sound source separation, musical acoustics, music
perception, or performance analysis. The basic model and
implementation was developed in the PhD thesis by X. Serra in 1989 and
since then many extensions have been proposed at MTG-UPF and by other
researchers.

\fIsmsClean\fP is used on .sms files that have been analyzed with \fIsmsAnal\fP.
In the case of inharmonic sounds there might be empty trajectories and also the trajectories are not ordered by frequency. This programs takes out the empty trajectories and orders the trajectories by frequency.

For more information, see the README included with the SMS package
or visit the SMS homepage at:
\fIhttp://www.iua.upf.es/~sms/\fP

.SH SEE ALSO
smsAnal(1), smsSynthDet(1), smsSynth(1), smsMod(1), smsPrint(1),
smsResample(1), smsUnDb(1)
