.TH smsPrint 1 "2008 Feb 22" GNU
.SH NAME
smsPrint - Program to print the SMS analysis files.
.SH SYNOPSIS
.B smsPrint
[-\fIoption\fP ...]
.I smsFile
.SH DESCRIPTION
\fISMS\fP is a set of techniques and software implementations for the
analysis, transformation and synthesis of musical sounds based on a
sinusoidal plus residual model. These techniques can be used for
synthesis, processing and coding applications, while some of the
intermediate results might also be applied to other music related
problems, such as sound source separation, musical acoustics, music
perception, or performance analysis. The basic model and
implementation was developed in the PhD thesis by X. Serra in 1989 and
since then many extensions have been proposed at MTG-UPF and by other
researchers.

This program prints on the screen in ASCII code the output of the smsAnal program.

For background information on how to create and synthesize SMS the analysis files, or what to do with 
it other than recreate the original, see the README included with the SMS package
or visit the SMS homepage at:
\fIhttp://www.iua.upf.es/~sms/\fP
.SH OPTIONS
.BI -t " type-format"
.B (default 1)
1 print all the information, 2 print only the deterministic component, 3 print only the stochastic component.
iwejrioqejrioqejfqewiofjqewfje0qfjqewiodjewioqdjqwiedjioqdjioqewjdoqeijdioqwedoiqdjoiqdj
.SH SEE ALSO
smsAnal(1), smsPrintDet(1), smsClean(1), smsMod(1), smsSynth(1),
smsResample(1), smsUnDb(1)
