.TH smsToYaml 1 "2008 Oct 13" GNU
.SH NAME
smsToYaml - Program to convert an SMS analysis files (binary) to YAML (text).
.SH SYNOPSIS
.B smsToYaml
[-\fIoption\fP ...]
.I smsFile
.SH DESCRIPTION
\fISMS\fP is a set of techniques and software implementations for the
analysis, transformation and synthesis of musical sounds based on a
sinusoidal plus residual model. These techniques can be used for
synthesis, processing and coding applications, while some of the
intermediate results might also be applied to other music related
problems, such as sound source separation, musical acoustics, music
perception, or performance analysis. The basic model and
implementation was developed in the PhD thesis by X. Serra in 1989 and
since then many extensions have been proposed at MTG-UPF and by other
researchers.

This program writes a text file in YAML format (\fIhttp://www.yaml.org/\f ) that is very easy to read. 
It can also be interpreted by other applications, such as python.

For background information on how to create and synthesize SMS the analysis files, or what to do with 
it other than recreate the original, see the README included with the SMS package
or visit the SMS homepage at:
\fIhttp://www.iua.upf.es/~sms/\fP
.SH OPTIONS
.BI -t " type-format"
.B (default 1)
1 write all the information, 2 write only the deterministic component, 3 write only the stochastic component.
.TP 8
.BI -i " initial-time"
.B (default 0)
when to start writing the analysis files from the input .sms file
.TP 8
.BI -i " end-time"
.B (default end-of-file)
when to stop writing the analysis files from the input .sms file

.SH SEE ALSO
smsAnal(1), smsClean(1), smsSynth(1), smsResample(1), smsPrint(1)
