#!/bin/bash

#- E minor Acoustic Guitar Chord
# http://www.freesound.org/download/8492/8492_SpeedY_Emin_full.wav
# (I chopped off all but the first few seconds of the sample)

# a guitar chord is inharmonic containing three independant notes,
# so trying to improve partial tracking by depending on a an overall
# harmonic structure is useless.  Instead, just track peaks from frame to frame.
# TRY: different windows (bh92)

# ---- questions ---
# analysis parameters:
# -f1: format inharmonic
# -i1: hamming window, allows for subband frequencies
# -l85: lowest frequency 85 hertz, right below the low E of a guitar
# -u88: sets the main window size to be large enough for 88 hertz
# -p200: 200 partials (seems that more the better in inharmonic sounds)
# -n300: 300 guides, probably not necessary
# -t1: set peakToContGuide to full so that new peaks get full contribution
# -c128: 128 stochastic coefficients (fft bins)
# -a.001: minimum track length is veeerry short (1 ms)
#smsAnal -f1 -q0 -i4 -l85 -h20000 -u88 -p200 -n300 -t1 -c128 -a.001 guitarchord.wav guitarchord.sms ;
smsAnal -f1 -q0 -i1 -l85 -u88 -p200 -n300 -t1 -c128 -a.0001 guitarchord.wav guitarchord.sms ;
smsPrint -t4 guitarchord.sms ;
smsSynth -s1 guitarchord.sms guitarchord.det.wav ;
# turning the residual down a little because it is too noisy
smsSynth -g.15 guitarchord.sms guitarchord.synth.wav ;
smsToYaml -t2 guitarchord.sms guitarchord.yaml