# -*- python -*-
# scons script for building tools

Import('env')


sms_tools = Split(' smsAnal smsSynth smsClean \
        	smsMod smsPrint smsResample \
        	smsToYaml' )

env.Append(LIBS = 'sms',  CPPPATH = '../src', LIBPATH = '../src')

for t in sms_tools:
	t_src = t+'.c'
	tool =env.Program( target = t, source = t_src)
        Depends(tool, '../src/libsms.a')
