
# -*- python -*-
# scons script for building tools

Import('*')

tools = Split(' smsAnal smsSynth smsClean \
        	smsPrint smsResample ' )

#where to install tools and manpages
tools_prefix = prefix+'/bin'
man_prefix = '/usr/share/man/man1'

env.Prepend(LIBS = 'sms',  CPPPATH = '#src', LIBPATH = '#src')
env.Prepend(LIBS = 'popt') # command line parsing

#build each tool
for t in tools:
	t_src = t+'.c'
	t_man = '../man/' + t +'.1'
	tool =env.Program( target = t, source = t_src)
        Depends(tool, '../src/libsms.a')
#        Depends(tool, '../src/libsms.so')
        #install tool
        env.Install(tools_prefix, t)
        env.Alias('install', tools_prefix)
        env.Install(man_prefix, t_man)
        env.Alias('install', man_prefix)



