/* 
 * Copyright (c) 2008 MUSIC TECHNOLOGY GROUP (MTG)
 *                         UNIVERSITAT POMPEU FABRA 
 * 
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of 
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 * 
 */
#include "../sms.h"

#define USAGE "Usage: smsToML <smsFile> <outputFile>"

short MaxDelayFrames;
float FResidualPerc;
SMS_SndBuffer soundBuffer, synthBuffer;
SMS_AnalFrame **ppFrames, *pFrames;

void main (int argc, char *argv[])
{
	SMS_Header *pSmsHeader;
	char *namedata;
	SMS_Data smsData;
	int iError, i, j;
	FILE *fp, *pSmsFile;

	if (argc != 3) 
		quit(USAGE);

	if((iError = sms_getHeader (argv[1], &pSmsHeader, &pSmsFile)) < 0)
	{
		if(iError == SMS_NOPEN)
			quit("cannot open file");
		if(iError == SMS_RDERR)
			quit("read error");
		if(iError == SMS_NSMS)
			quit("not an SMS file");
		if(iError == SMS_MALLOC)
			quit("cannot allocate memory");
		quit("error");
	}	    
    
	sms_allocFrameH (pSmsHeader, &smsData);

	fp = fopen(argv[2],"w");
	namedata = (char *)strtok (argv[2],".");

	fprintf(fp,"%% This matlab file was generated by smsToML.\n");
	fprintf(fp,"%% The principal variables defined below are \n");
	fprintf(fp,"%% %s_amps, %s_freqs, ", namedata, namedata);
	fprintf(fp, "(if applicable) %s_phases and %s_coeffs.\n", namedata, namedata);
	fprintf(fp,"%% Also defined are header variables and an args string.\n");
	fprintf(fp,"%% All variable names are prefixed by '%s_'.\n", namedata);

	fprintf(fp,"\n%% HEADER INFORMATION:\n");
	fprintf(fp,"%s_nrec = %d;\n", namedata, pSmsHeader->nFrames);
	fprintf(fp,"%s_framerate = %d;\n", namedata, pSmsHeader->iFrameRate);
	fprintf(fp,"%s_ntraj = %d;\n", namedata, pSmsHeader->nTrajectories);
	fprintf(fp,"%s_nstoccoeffs = %d;\n", namedata, pSmsHeader->nStochasticCoeff);
	fprintf(fp,"%s_format = %d;\n", namedata, pSmsHeader->iFormat);
	fprintf(fp,"%s_stoctype = %d;\n", namedata, pSmsHeader->iStochasticType);
	fprintf(fp,"%s_origsrate = %d;\n", namedata, pSmsHeader->iOriginalSRate);
            
	fprintf(fp,"\n%s_amps = zeros(%s_nrec,%s_ntraj);\n", namedata, namedata, 
	        namedata);

	for(i = 0; i < pSmsHeader->nFrames; i++)
	{
		sms_getFrame (pSmsFile, pSmsHeader, i, &smsData);
		fprintf(fp,"%s_amps(%d,:) = [", namedata, i+1);
		for(j = 0; j < smsData.nTraj; j++)
			fprintf(fp," %.2f", smsData.pFSinMag[j]);
		fprintf(fp," ];\n");
	}
      
	fprintf(fp,"\n%s_freqs = zeros(%s_nrec, %s_ntraj);\n", namedata, namedata, 
	        namedata);
	for(i = 0; i < pSmsHeader->nFrames; i++)
	{
		sms_getFrame (pSmsFile, pSmsHeader, i, &smsData);
		fprintf(fp,"%s_freqs(%d,:) = [", namedata, i+1);
		for(j = 0; j < smsData.nTraj; j++)
			fprintf(fp," %.2f", smsData.pFSinFreq[j]);
		fprintf(fp,"];\n");
	}
      
	if (!(pSmsHeader->iFormat == SMS_FORMAT_H ||
	     pSmsHeader->iFormat == SMS_FORMAT_IH))
	{
		fprintf(fp,"\n%s_phases = zeros(%s_nrec,%s_ntraj);\n", namedata, namedata, 
	            namedata);
		for(i = 0; i < pSmsHeader->nFrames; i++)
		{
			sms_getFrame (pSmsFile, pSmsHeader, i, &smsData);
			fprintf(fp,"%s_phases(%d,:) = [", namedata, i+1);
			for(j = 0; j < smsData.nTraj; j++)
				fprintf(fp," %.2f", smsData.pFSinPha[j]);
			fprintf(fp," ];\n");
		}
	}
	if (pSmsHeader->iStochasticType != SMS_STOC_NONE) 
	{		   
		fprintf(fp,"\n%s_stoccoeffs = zeros(%s_nrec, %s_nstoccoeffs);\n", namedata, 
		        namedata, namedata);
		for(i = 0; i < pSmsHeader->nFrames; i++)
		{
			sms_getFrame (pSmsFile, pSmsHeader, i, &smsData);
			fprintf(fp,"%s_stoccoeffs(%d,:) = [", namedata, i+1);
			for(j = 0; j < smsData.nCoeff; j++)
				fprintf(fp," %.4f", smsData.pFStocCoeff[j]);
			fprintf(fp," ];\n");
		} 
		fprintf(fp,"\n%s_stocgain = zeros(1, %s_nrec);\n", namedata, 
		        namedata);
		for(i = 0; i < pSmsHeader->nFrames; i++)
		{
			sms_getFrame (pSmsFile, pSmsHeader, i, &smsData);
			fprintf(fp,"%s_stocgain (%d) = %.4f ;\n", namedata, i+1, 
				*(smsData.pFStocGain));
		}  
	}   
	fprintf(fp,"\ndisp('Defined variables %s_*.  Say whos for details.');\n",
	        namedata);
 
	fclose (pSmsFile);
	fclose (fp);
	exit(0);
}
