# -*- python -*-
# scons script for libsms source directory

Import('*')

lib_prefix = prefix+'/lib'
header_prefix = prefix+'/include'
header = "sms.h"
env.Alias('install', lib_prefix);
env.Alias('install', header_prefix)

sms_sources = Split("""
                sms.c 
                analysis.c 
		synthesis.c 
                sineSynth.c 
		peakDetection.c 
                harmDetection.c 
                peakContinuation.c 
		stocAnalysis.c 
		getResidual.c 
                spectralApprox.c 
		spectrum.c 
                fixTracks.c 
                transforms.c 
                filters.c 
                tables.c 
                windows.c 
                fileIO.c 
		soundIO.c 
                hybridize.c
                OOURA.c
                SFMT.c
""")

lib = env.Library( 'libsms', sms_sources )
#lib = env.SharedLibrary( 'libsms', sms_sources )
env.Install(lib_prefix, lib) 
env.Install(header_prefix, header)
